## Preprocessing Data

In [45]:
import pandas as pd 

df = pd.read_csv("../data.csv")
print("Original dataset shape:", df.shape)
df.head()

Original dataset shape: (974, 3)

   Temp  Humd  Label
0  23.0    17      1
1  23.0    17      1
2  23.0    17      1
3  23.0    17      1
4  23.0    17      1

Adding False values:

In [46]:
import pandas as pd # in case of error, install pnadas using: pip install pandas
import random

random.seed(42) #makes sure that the random numbers generated are the same every time you run the code.
 
# Read the CSV file into a DataFrame

df = pd.read_csv("../data.csv")

false_rows = []

for i in range(100):
    
    false_rows.append({       #using random integers to generate false data.
        "Temp": random.randint(-100, 200),
        "Humd": random.randint(0, 100), 
        "Label": 0
    })
    
df_new = pd.DataFrame(false_rows)
df = pd.concat([df, df_new], ignore_index=True)

# Step 3: Save the DataFrame to a new CSV file
df.to_csv("data_hacked.csv", index=False)

print("New dataset shape:", df.shape)
df.head()
df.tail()

New dataset shape: (1074, 3)

       Temp  Humd  Label
1069  172.0    98      0
1070  -36.0    16      0
1071  143.0    70      0
1072  -16.0    33      0
1073  170.0    77      0

Data Pre processing:

In [47]:
# Check for missing values
missing_values = df.isnull().sum()
print("Missing Values:\n", missing_values)

#remove duplicates
df = df.drop_duplicates()
print("processed dataset shape:", df.shape)

Missing Values:
 Temp     0
Humd     0
Label    0
dtype: int64
processed dataset shape: (147, 3)

Feature prep

In [48]:
# prepare features
x = df.drop(['Label'],axis=1) #remove class or label
y = df['Label'] #load label

data split:

In [49]:

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler #module for perform scaling

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,  random_state=42)

# Scale the data using standardization
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train) #scale training set
x_test = scaler.transform(x_test) #scale test set

## Algorithm 1: Linear Classification

In [ ]:
from sklearn.linear_model import LogisticRegression





logreg = LogisticRegression()
logreg.fit(x_train, y_train)

print("Training score: {:.3f}".format(logreg.score(x_train, y_train)))
print("Test score: {:.3f}".format(logreg.score(x_test, y_test)))

Training score: 0.607
Test score: 0.467

## Algorithm 2: K nearest

In [51]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5 )
knn.fit(x_train, y_train)

print("Training score: {:.3f}".format(knn.score(x_train, y_train)))
print("Test score: {:.3f}".format(knn.score(x_test, y_test)))

Training score: 0.915
Test score: 1.000

## Algorithm 3: Descision tree

In [52]:
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(random_state=42)
tree.fit(x_train, y_train)

print("Training score: {:.3f}".format(tree.score(x_train, y_train)))
print("Test score: {:.3f}".format(tree.score(x_test, y_test)))

Training score: 1.000
Test score: 0.967

## Algorithm 3: Descision tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(random_state=42)
tree.fit(x_train, y_train)

print("Training score: {:.3f}".format(tree.score(x_train, y_train)))
print("Test score: {:.3f}".format(tree.score(x_test, y_test)))

Training score: 1.000
Test score: 0.967